export const CURRENCIES = {
    SET_CURRENCIES: 'SET_CURRENCIES',
    SET_DATE: 'SET_DATE',
    SET_BASE_CODE: 'SET_BASE_CODE',
    SET_FIRST_CODE: 'SET_FIRST_CODE',
    SET_SECOND_CODE: 'SET_SECOND_CODE',
    SET_FIRST_VALUE: 'SET_FIRST_VALUE',
    SET_SECOND_VALUE: 'SET_SECOND_VALUE',
    CHANGE_FIRST_VALUE: 'CHANGE_FIRST_VALUE',
    CHANGE_SECOND_VALUE: 'CHANGE_SECOND_VALUE',
};

export const ERROR = {
    SERVER: 'SERVER',
    API: 'API',
};